"""initial schema

Revision ID: b51d7e5c38b0
Revises: 
Create Date: 2026-03-08 17:06:45.439545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51d7e5c38b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('prefecture', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('home_latitude', sa.Float(), nullable=True),
    sa.Column('home_longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_line_id'), 'users', ['line_id'], unique=True)
    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='GPSデバイスID'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    op.create_table('danger_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False, comment='危険地点の緯度'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='危険地点の経度'),
    sa.Column('radius_meters', sa.Float(), nullable=True, comment='影響半径 (メートル)'),
    sa.Column('risk_level', sa.Integer(), nullable=False, comment='リスクレベル (1-10)'),
    sa.Column('risk_type', sa.Enum('SUSPICIOUS_PERSON', 'TRAFFIC', 'CRIME', 'DARK_AREA', 'CONSTRUCTION', 'NATURAL_HAZARD', 'OTHER', name='risk_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('POLICE', 'COMMUNITY', 'AI_ANALYSIS', 'GOVERNMENT', 'SCHOOL', name='danger_zone_source'), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='有効期限'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='確認済みかどうか'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('ROUTE_DEVIATION', 'SPEED_ANOMALY', 'ZONE_ENTRY', 'SOS', 'BATTERY_LOW', 'DEVICE_OFFLINE', 'GEOFENCE_EXIT', 'ARRIVAL', 'DEPARTURE', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', 'EMERGENCY', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_child_id'), 'alerts', ['child_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True, comment='移動速度 (m/s)'),
    sa.Column('accuracy', sa.Float(), nullable=True, comment='精度 (メートル)'),
    sa.Column('heading', sa.Float(), nullable=True, comment='方位角 (度)'),
    sa.Column('source', sa.Enum('GPS_DEVICE', 'APP', 'MANUAL', name='location_source'), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=True, comment='デバイスバッテリー残量 (%)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_child_id'), 'locations', ['child_id'], unique=False)
    op.create_index(op.f('ix_locations_timestamp'), 'locations', ['timestamp'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False, comment='出発地点の緯度'),
    sa.Column('origin_lng', sa.Float(), nullable=False, comment='出発地点の経度'),
    sa.Column('destination_lat', sa.Float(), nullable=False, comment='目的地点の緯度'),
    sa.Column('destination_lng', sa.Float(), nullable=False, comment='目的地点の経度'),
    sa.Column('waypoints_json', sa.JSON(), nullable=True, comment='経由ポイント [{lat, lng, order, safety_score}]'),
    sa.Column('distance_meters', sa.Float(), nullable=True, comment='距離 (メートル)'),
    sa.Column('estimated_duration_minutes', sa.Float(), nullable=True, comment='予想所要時間 (分)'),
    sa.Column('safety_score', sa.Float(), nullable=False, comment='安全スコア (1-10)'),
    sa.Column('is_recommended', sa.Boolean(), nullable=False, comment='推奨ルートかどうか'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_child_id'), 'routes', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_child_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_locations_timestamp'), table_name='locations')
    op.drop_index(op.f('ix_locations_child_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_child_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('danger_zones')
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_users_line_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
